probe_types:
  environment:
    description: "Reflections on the development environment and setup"
    templates:
      - "How does your current development environment affect your productivity?"
      - "What aspects of your workspace help you focus the most?"
      - "Which environmental factors (noise, lighting, etc.) impact your coding?"
  
  tools:
    description: "Insights about development tools and their usage"
    templates:
      - "Which IDE features do you use most frequently?"
      - "Are there any missing tools that would improve your workflow?"
      - "How do your current tools support or hinder your coding process?"
  
  workflow:
    description: "Understanding development processes and patterns"
    templates:
      - "How do you typically break down complex coding tasks?"
      - "What's your preferred way to tackle debugging?"
      - "How do you balance feature development with code maintenance?"
  
  sustainability:
    description: "Exploring sustainable coding practices"
    templates:
      - "How do you consider resource usage when choosing libraries?"
      - "What practices do you follow to optimize code efficiency?"
      - "How do you balance performance with energy consumption?"

probe_settings:
  frequency:
    comments: "daily"      # How often to inject new probe comments
    tasks: "weekly"        # Frequency of task-based probes
    commits: "per-commit"  # Prompt frequency during commits
  
  storage:
    location: ".probe_responses"  # Where to store probe responses
    format: "markdown"           # Response storage format
    allowed_formats:            # Support multiple response types
      - "text"
      - "image"
      - "audio"
      - "diagram"
      - "sketch"
    media_directory: ".probe_responses/media"  # Store media files
  
  accessibility:
    support_voice_input: true    # Enable voice input for responses
    support_dark_mode: true      # Support dark mode for templates
    font_size_adjustable: true   # Allow font size customization
    emoji_support: true          # Use emojis for visual cues
    screen_reader_friendly: true # Ensure screen reader compatibility
  
  privacy:
    collect_environment: false   # Don't collect environment data automatically
    collect_metrics: false       # Don't collect usage metrics
    anonymize: true             # Anonymize all responses

submission_settings:
  receiver_email: "elric.ettmueller@hm.edu"
  submission_format:
    include_system_info: true
    include_timestamps: true
    generate_qr: true
  pdf_settings:
    template: "default"
    include_cover_page: true
    page_numbers: true
    watermark: "Confidential Research Data"
  security:
    encrypt_zip: true
    generate_checksum: true
    file_protection:
      enabled: true
      protected_paths:
        - "02_your_task/examples"
        - "03_reflection/templates"
        - ".probe_responses"
      exclude_from_protection:
        - ".gitkeep"
        - "README.md"
        - "TEMPLATE_*.md"
  metadata:
    institution: "Munich University of Applied Sciences"
    research_project: "Cultural Probes Study"
    contact_info: "elric.ettmueller@hm.edu"
    data_handling_notice: >
      All submitted data will be handled confidentially and used solely for research purposes.
      By submitting this data, you agree to our research data handling policies.

email_template: |
  Subject: Cultural Probe Submission - {submission_id}
  
  Dear Research Team,
  
  Please find attached my Cultural Probe submission (ID: {submission_id}).
  
  Submission Details:
  - Timestamp: {timestamp}
  - Number of Responses: {num_responses}
  - Checksum: {checksum}
  
  Best regards,
  {participant_name}

directories:
  responses: ".probe_responses"
  submissions: "04_submission/submissions"
  templates: "04_submission/templates"
